version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./web/dth.com.vn/public_html:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf  # Gán cấu hình Nginx tùy chỉnh
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
